// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: bol_service_v1beta1/bol-service.proto

package bol_service

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	bol_api_proto_go "gitlab.com/tcorp-k8s/protos/bol-api-proto-go"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FulfilmentMethod int32

const (
	FulfilmentMethod_FBR FulfilmentMethod = 0
	FulfilmentMethod_FBB FulfilmentMethod = 1
)

// Enum value maps for FulfilmentMethod.
var (
	FulfilmentMethod_name = map[int32]string{
		0: "FBR",
		1: "FBB",
	}
	FulfilmentMethod_value = map[string]int32{
		"FBR": 0,
		"FBB": 1,
	}
)

func (x FulfilmentMethod) Enum() *FulfilmentMethod {
	p := new(FulfilmentMethod)
	*p = x
	return p
}

func (x FulfilmentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FulfilmentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_bol_service_v1beta1_bol_service_proto_enumTypes[0].Descriptor()
}

func (FulfilmentMethod) Type() protoreflect.EnumType {
	return &file_bol_service_v1beta1_bol_service_proto_enumTypes[0]
}

func (x FulfilmentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FulfilmentMethod.Descriptor instead.
func (FulfilmentMethod) EnumDescriptor() ([]byte, []int) {
	return file_bol_service_v1beta1_bol_service_proto_rawDescGZIP(), []int{0}
}

type GetShipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique id of the shipment, required
	ShipmentId string `protobuf:"bytes,1,opt,name=shipmentId,proto3" json:"shipmentId,omitempty"`
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_service_v1beta1_bol_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bol_service_v1beta1_bol_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_bol_service_v1beta1_bol_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetShipmentRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type GetShipmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The shipment
	Shipment *bol_api_proto_go.Shipment `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
}

func (x *GetShipmentResponse) Reset() {
	*x = GetShipmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_service_v1beta1_bol_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentResponse) ProtoMessage() {}

func (x *GetShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bol_service_v1beta1_bol_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentResponse) Descriptor() ([]byte, []int) {
	return file_bol_service_v1beta1_bol_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetShipmentResponse) GetShipment() *bol_api_proto_go.Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type GetShipmentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pager  *Pager           `protobuf:"bytes,1,opt,name=pager,proto3" json:"pager,omitempty"`
	Method FulfilmentMethod `protobuf:"varint,2,opt,name=method,proto3,enum=bol_service_v1beta1.FulfilmentMethod" json:"method,omitempty"`
}

func (x *GetShipmentsRequest) Reset() {
	*x = GetShipmentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_service_v1beta1_bol_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShipmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentsRequest) ProtoMessage() {}

func (x *GetShipmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bol_service_v1beta1_bol_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentsRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentsRequest) Descriptor() ([]byte, []int) {
	return file_bol_service_v1beta1_bol_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetShipmentsRequest) GetPager() *Pager {
	if x != nil {
		return x.Pager
	}
	return nil
}

func (x *GetShipmentsRequest) GetMethod() FulfilmentMethod {
	if x != nil {
		return x.Method
	}
	return FulfilmentMethod_FBR
}

// You should only assume there are no new products when the server returns 0 products.
// In case your ascending you can also add another check when the latest timestamp comes close to the present.
// This way you don't keep following up on newly added products.
type ListProductRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pager *Pager `protobuf:"bytes,1,opt,name=pager,proto3" json:"pager,omitempty"` // Handles the paging for this list
}

func (x *ListProductRequest) Reset() {
	*x = ListProductRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_service_v1beta1_bol_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductRequest) ProtoMessage() {}

func (x *ListProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bol_service_v1beta1_bol_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductRequest.ProtoReflect.Descriptor instead.
func (*ListProductRequest) Descriptor() ([]byte, []int) {
	return file_bol_service_v1beta1_bol_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductRequest) GetPager() *Pager {
	if x != nil {
		return x.Pager
	}
	return nil
}

// A pager helps with paging through lists of resources.
// We recommend listing in descending from the current time until there are no more resources.
type Pager struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The maximum amount of items to return. The server may also enforce a maximum server-side (Default is around 100).
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Start the list from this timestamp, set ascending to list items with a createdTimestamp greater then fromTimestamp,
	// descending from less then.
	FromTimestamp int64 `protobuf:"varint,2,opt,name=fromTimestamp,proto3" json:"fromTimestamp,omitempty"`
	// if set to true it will return items created after fromTimestamp, otherwise before fromTimestamp.
	Ascending bool `protobuf:"varint,3,opt,name=ascending,proto3" json:"ascending,omitempty"`
}

func (x *Pager) Reset() {
	*x = Pager{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bol_service_v1beta1_bol_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pager) ProtoMessage() {}

func (x *Pager) ProtoReflect() protoreflect.Message {
	mi := &file_bol_service_v1beta1_bol_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pager.ProtoReflect.Descriptor instead.
func (*Pager) Descriptor() ([]byte, []int) {
	return file_bol_service_v1beta1_bol_service_proto_rawDescGZIP(), []int{4}
}

func (x *Pager) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pager) GetFromTimestamp() int64 {
	if x != nil {
		return x.FromTimestamp
	}
	return 0
}

func (x *Pager) GetAscending() bool {
	if x != nil {
		return x.Ascending
	}
	return false
}

var File_bol_service_v1beta1_bol_service_proto protoreflect.FileDescriptor

var file_bol_service_v1beta1_bol_service_proto_rawDesc = []byte{
	0x0a, 0x25, 0x62, 0x6f, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x62, 0x6f, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x62, 0x6f, 0x6c, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x1a, 0x23, 0x62, 0x6f,
	0x6c, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x2f, 0x62, 0x6f, 0x6c, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x34, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x68, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x68,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x08, 0x73, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x86, 0x01, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x53, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x05,
	0x70, 0x61, 0x67, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x46, 0x75, 0x6c, 0x66,
	0x69, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x22, 0x46, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x70, 0x61,
	0x67, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x6f, 0x6c, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x72, 0x22, 0x61, 0x0a, 0x05,
	0x50, 0x61, 0x67, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x66,
	0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2a,
	0x24, 0x0a, 0x10, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x42, 0x52, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x46, 0x42, 0x42, 0x10, 0x01, 0x32, 0xcb, 0x01, 0x0a, 0x0a, 0x42, 0x6f, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x0b, 0x67, 0x65, 0x74, 0x53, 0x68, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x27, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x62,
	0x6f, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x53, 0x68, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x28, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x62, 0x6f, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x30, 0x01, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x63, 0x6f, 0x72, 0x70, 0x2d, 0x6b, 0x38, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x62, 0x6f, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bol_service_v1beta1_bol_service_proto_rawDescOnce sync.Once
	file_bol_service_v1beta1_bol_service_proto_rawDescData = file_bol_service_v1beta1_bol_service_proto_rawDesc
)

func file_bol_service_v1beta1_bol_service_proto_rawDescGZIP() []byte {
	file_bol_service_v1beta1_bol_service_proto_rawDescOnce.Do(func() {
		file_bol_service_v1beta1_bol_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bol_service_v1beta1_bol_service_proto_rawDescData)
	})
	return file_bol_service_v1beta1_bol_service_proto_rawDescData
}

var file_bol_service_v1beta1_bol_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bol_service_v1beta1_bol_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bol_service_v1beta1_bol_service_proto_goTypes = []interface{}{
	(FulfilmentMethod)(0),             // 0: bol_service_v1beta1.FulfilmentMethod
	(*GetShipmentRequest)(nil),        // 1: bol_service_v1beta1.GetShipmentRequest
	(*GetShipmentResponse)(nil),       // 2: bol_service_v1beta1.GetShipmentResponse
	(*GetShipmentsRequest)(nil),       // 3: bol_service_v1beta1.GetShipmentsRequest
	(*ListProductRequest)(nil),        // 4: bol_service_v1beta1.ListProductRequest
	(*Pager)(nil),                     // 5: bol_service_v1beta1.Pager
	(*bol_api_proto_go.Shipment)(nil), // 6: bol_api_proto_v1beta1.Shipment
}
var file_bol_service_v1beta1_bol_service_proto_depIdxs = []int32{
	6, // 0: bol_service_v1beta1.GetShipmentResponse.shipment:type_name -> bol_api_proto_v1beta1.Shipment
	5, // 1: bol_service_v1beta1.GetShipmentsRequest.pager:type_name -> bol_service_v1beta1.Pager
	0, // 2: bol_service_v1beta1.GetShipmentsRequest.method:type_name -> bol_service_v1beta1.FulfilmentMethod
	5, // 3: bol_service_v1beta1.ListProductRequest.pager:type_name -> bol_service_v1beta1.Pager
	1, // 4: bol_service_v1beta1.BolService.getShipment:input_type -> bol_service_v1beta1.GetShipmentRequest
	3, // 5: bol_service_v1beta1.BolService.getShipments:input_type -> bol_service_v1beta1.GetShipmentsRequest
	2, // 6: bol_service_v1beta1.BolService.getShipment:output_type -> bol_service_v1beta1.GetShipmentResponse
	6, // 7: bol_service_v1beta1.BolService.getShipments:output_type -> bol_api_proto_v1beta1.Shipment
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bol_service_v1beta1_bol_service_proto_init() }
func file_bol_service_v1beta1_bol_service_proto_init() {
	if File_bol_service_v1beta1_bol_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bol_service_v1beta1_bol_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_service_v1beta1_bol_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShipmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_service_v1beta1_bol_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShipmentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_service_v1beta1_bol_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProductRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bol_service_v1beta1_bol_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pager); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bol_service_v1beta1_bol_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bol_service_v1beta1_bol_service_proto_goTypes,
		DependencyIndexes: file_bol_service_v1beta1_bol_service_proto_depIdxs,
		EnumInfos:         file_bol_service_v1beta1_bol_service_proto_enumTypes,
		MessageInfos:      file_bol_service_v1beta1_bol_service_proto_msgTypes,
	}.Build()
	File_bol_service_v1beta1_bol_service_proto = out.File
	file_bol_service_v1beta1_bol_service_proto_rawDesc = nil
	file_bol_service_v1beta1_bol_service_proto_goTypes = nil
	file_bol_service_v1beta1_bol_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BolServiceClient is the client API for BolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BolServiceClient interface {
	// Add a product to the catalog
	GetShipment(ctx context.Context, in *GetShipmentRequest, opts ...grpc.CallOption) (*GetShipmentResponse, error)
	// Gets a product from the catalog, identified by its ID or EAN
	GetShipments(ctx context.Context, in *GetShipmentsRequest, opts ...grpc.CallOption) (BolService_GetShipmentsClient, error)
}

type bolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBolServiceClient(cc grpc.ClientConnInterface) BolServiceClient {
	return &bolServiceClient{cc}
}

func (c *bolServiceClient) GetShipment(ctx context.Context, in *GetShipmentRequest, opts ...grpc.CallOption) (*GetShipmentResponse, error) {
	out := new(GetShipmentResponse)
	err := c.cc.Invoke(ctx, "/bol_service_v1beta1.BolService/getShipment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bolServiceClient) GetShipments(ctx context.Context, in *GetShipmentsRequest, opts ...grpc.CallOption) (BolService_GetShipmentsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BolService_serviceDesc.Streams[0], "/bol_service_v1beta1.BolService/getShipments", opts...)
	if err != nil {
		return nil, err
	}
	x := &bolServiceGetShipmentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BolService_GetShipmentsClient interface {
	Recv() (*bol_api_proto_go.Shipment, error)
	grpc.ClientStream
}

type bolServiceGetShipmentsClient struct {
	grpc.ClientStream
}

func (x *bolServiceGetShipmentsClient) Recv() (*bol_api_proto_go.Shipment, error) {
	m := new(bol_api_proto_go.Shipment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BolServiceServer is the server API for BolService service.
type BolServiceServer interface {
	// Add a product to the catalog
	GetShipment(context.Context, *GetShipmentRequest) (*GetShipmentResponse, error)
	// Gets a product from the catalog, identified by its ID or EAN
	GetShipments(*GetShipmentsRequest, BolService_GetShipmentsServer) error
}

// UnimplementedBolServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBolServiceServer struct {
}

func (*UnimplementedBolServiceServer) GetShipment(context.Context, *GetShipmentRequest) (*GetShipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShipment not implemented")
}
func (*UnimplementedBolServiceServer) GetShipments(*GetShipmentsRequest, BolService_GetShipmentsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetShipments not implemented")
}

func RegisterBolServiceServer(s *grpc.Server, srv BolServiceServer) {
	s.RegisterService(&_BolService_serviceDesc, srv)
}

func _BolService_GetShipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BolServiceServer).GetShipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bol_service_v1beta1.BolService/GetShipment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BolServiceServer).GetShipment(ctx, req.(*GetShipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BolService_GetShipments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetShipmentsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BolServiceServer).GetShipments(m, &bolServiceGetShipmentsServer{stream})
}

type BolService_GetShipmentsServer interface {
	Send(*bol_api_proto_go.Shipment) error
	grpc.ServerStream
}

type bolServiceGetShipmentsServer struct {
	grpc.ServerStream
}

func (x *bolServiceGetShipmentsServer) Send(m *bol_api_proto_go.Shipment) error {
	return x.ServerStream.SendMsg(m)
}

var _BolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bol_service_v1beta1.BolService",
	HandlerType: (*BolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getShipment",
			Handler:    _BolService_GetShipment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getShipments",
			Handler:       _BolService_GetShipments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bol_service_v1beta1/bol-service.proto",
}
